version: '3'
services:
  post-db:
    image: postgres
  post-ms:
    build: .
    command:
      bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:drop db:create db:migrate db:seed && bundle exec rails server -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - post-db
